### ISSUE TITLE
Profile pic not showing consistently

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate-admin#24] opened 2015-06-18 18:31 UTC
Some users have the profile pic icon showing in the student list section. In the attached screen shot, Chris has a profile pic on the right but not on the left.

![screen shot 2015-06-18 at 2 28 23 pm](https://cloud.githubusercontent.com/assets/5123794/8238926/b1d957a0-15c6-11e5-97bc-c196e81f8c62.png)

**Comment by themightychris** [comment] 2015-06-26 04:17
@ckunkel I can't reproduce this, it might just have been a hiccup on your computer with downloading the new thumbnail, it looks like it should be using the same source for both. Please test again on v2.slate.is and close this if you can't reproduce either

**Closed** 2015-06-26 12:52 UTC
Labels: bug
