### ISSUE TITLE
Expanding certain tree items collapses entire tree

### ISSUE THREAD

**Issue by ryon** [SlateFoundation/slate-admin#69] opened 2015-09-09 23:05 UTC
Perhaps a duplicate ID issue?

**Steps**

1. Load /SlateAdmin/?apiHost=demo.v2.slate.is/#settings/groups
2. Expand Alumni
3. Attempt to expand Class of 2014

**Expected**
Class of 2014 expands

**Actual**
Alumni collapses, along with any other open nodes

**Comment by aharley40** [comment] 2015-09-10 13:11
@ryon I couldn't reproduce this. Are there any more steps?

**Comment by themightychris** [comment] 2015-09-10 14:05
@ryon try this out on an updated build today, it might have been accidentally fixed in another issue

**Comment by ryon** [comment] 2015-09-10 20:31
@themightychris Still happens for me. `development` branch, `demo.v2.slate.is` as the `apiHost`.

**Comment by themightychris** [comment] 2015-09-10 20:49
It was an issue with a leaf state corruption in the backend table

**Closed by themightychris** 2015-09-10 20:49 UTC
